services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: esp32db
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: always
    working_dir: /app
    networks:
      - my_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    restart: always
    working_dir: /app
    networks:
      - my_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  db:
    driver: local

networks:
  my_network:
    driver: bridge
